# .github/workflows/sync-to-hf.yml
name: Sync to Hugging Face

on:
  push:
    branches: [ main ]
    paths:
      - 'README.md'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create combined README
        run: |
          # Create temporary file with HF front matter and dataset card
          cat > temp_readme.md << 'EOL'
          [Previous front matter content...]
          EOL
          
          cat README.md >> temp_readme.md
          cat >> temp_readme.md << 'EOL'
          [Previous additional content...]
          EOL
          mv temp_readme.md README.md

      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
      - name: Clone and Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git clone "https://$HF_TOKEN@huggingface.co/datasets/danielrosehill/LLM-Assistant-Library" hf_repo
          cp README.md hf_repo/
          cd hf_repo
          git add README.md
          git commit -m "Sync README from GitHub"
          git push origin main