name: Sync to Hugging Face

on:
  push:
    branches: [ main ]
    paths:
      - 'README.md'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Hugging Face CLI
        run: |
          pip install --upgrade huggingface_hub
          
      - name: Login to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          huggingface-cli login --token $HF_TOKEN

      - name: Create combined README
        run: |
          # Create temporary file with HF front matter
          cat > temp_readme.md << 'EOL'
          ---
          license: apache-2.0
          annotations_creators:
          - expert-generated
          language:
          - en
          language_creators:
          - expert-generated
          size_categories:
          - n<1K
          source_datasets:
          - original
          task_categories:
          - text-generation
          - conversational
          task_ids:
          - dialogue-modeling
          - text-generation
          paperswithcode_id: null
          pretty_name: LLM Assistant Library
          tags:
          - llm-agents
          - prompts
          - system-prompts
          ---

          EOL
          
          cat README.md >> temp_readme.md
          mv temp_readme.md README.md

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git clone "https://huggingface.co/datasets/danielrosehill/LLM-Assistant-Library" hf_repo
          cp README.md hf_repo/
          cd hf_repo
          git add README.md
          git commit -m "Sync README from GitHub"
          git push "https://user:$HF_TOKEN@huggingface.co/datasets/danielrosehill/LLM-Assistant-Library" main